language: c
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    update: true
    packages:
      - cmake
install:
  - pushd $HOME
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -Sy
  - sudo dkp-pacman -Syu
  - sudo dkp-pacman -S -v --noconfirm devkitARM gba-tools
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - travis_retry git clone https://github.com/pret/agbcc.git
  - cd agbcc && ./build.sh
  - export AGBCC=$(pwd)
  - travis_retry git clone https://github.com/pret/pokeruby.git
  - cd pokeruby && ./build_tools.sh
  - export POKERUBY=$(pwd)
  - popd
script:
  - mkdir -p build
  - cd build
  - /usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=../gba.toolchain.cmake ..
  - make
