on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2

      - name: "Install tools"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc libpng-dev -y

      - run: |
          version=3.x
          build=3
          mkdir temp
          cd temp
          wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          tar -xzvf cmake-$version.$build.tar.gz
          cd cmake-$version.$build/
          ./bootstrap
          make -j4
          sudo make install
        shell: bash
      - run: cmake --version

#      - uses: actions/checkout@v2
#        with:
#          repository: pret/agbcc
#          path: agbcc
#      - run: ./build.sh
#        working-directory: agbcc
#
#      - uses: actions/checkout@v2
#        with:
#          repository: pret/pokeruby
#          path: pokeruby
#      - run: ./build_tools.sh
#        working-directory: pokeruby

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        run: cmake ..
        working-directory: ${{ github.workspace }}/build

      - run: make
        working-directory: ${{ github.workspace }}/build

      - run: make validate
        working-directory: ${{ github.workspace }}/build
