on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2

      - name: "Install tools"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc libpng-dev -y
      - run: cmake --version

#      - uses: actions/checkout@v2
#        with:
#          repository: pret/agbcc
#          path: agbcc
#      - run: ./build.sh
#        working-directory: agbcc
#
#      - uses: actions/checkout@v2
#        with:
#          repository: pret/pokeruby
#          path: pokeruby
#      - run: ./build_tools.sh
#        working-directory: pokeruby

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        run: cmake
        working-directory: ${{runner.workspace}}/build

      - run: make
        working-directory: ${{runner.workspace}}/build

      - run: make validate
        working-directory: ${{runner.workspace}}/build
