on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2

      - name: "Install tools"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc libpng-dev -y

      - run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget -y
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
          sudo apt-get update
          sudo apt-get install cmake -y
      - run: cmake --version

#      - uses: actions/checkout@v2
#        with:
#          repository: pret/agbcc
#          path: agbcc
#      - run: ./build.sh
#        working-directory: agbcc
#
#      - uses: actions/checkout@v2
#        with:
#          repository: pret/pokeruby
#          path: pokeruby
#      - run: ./build_tools.sh
#        working-directory: pokeruby

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        run: cmake ..
        working-directory: ${{ github.workspace }}/build

      - run: make
        working-directory: ${{ github.workspace }}/build

      - run: make validate
        working-directory: ${{ github.workspace }}/build
